name: donor_app
description: A donor module of the FYP

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #intl: ^0.18.0
  #intl: ^0.17.0-nullsafety.2
  #intl: ^0.17.0
  firebase_auth: ^4.2.2
  easy_localization: ^3.0.1
  translator: ^0.1.7
  # easypaisa_flutter: ^1.0.0
  # provider: ^4.1.2
  permission_handler: ^10.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  #google_fonts: ^3.0.1
  pie_chart: ^5.3.2
  custom_navigation_bar: ^0.8.2
  #firebase_auth: ^4.4.2
  #firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  pinput: ^2.2.31
  get: ^4.6.5
  provider: ^6.0.5
  modal_progress_hud_nsn: ^0.2.1
  google_maps_flutter: ^2.2.4
  location: ^4.4.0
  flutter_polyline_points: ^1.0.0
  d_chart: ^2.2.11
  flutter_map: ^3.1.0
  geolocator: ^9.0.2
  flutter_svg: ^2.0.5
  table_calendar: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - translations/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Thin.ttf
    - family: Nastaleeq
      fonts:
        - asset: fonts/Nastaleeq.ttf
